### PR TITLE
update to bootstrap 5

### PR DESCRIPTION
**Pull request by achimgaedke**
Hi Oege!

Here's a WIP pull request porting this project to bootstrap-5, it was lying around for a month...

There are two show stoppers I know of:

* dash-auth is not updated to dash-2, but https://github.com/plotly/dash-auth/pull/125 fills this gap
* I haven't updated the `to_html` functions to bootstrap-5

I also haven't actually tested the dashboard systematically, just the titanic classifier and played a little bit with the hub.

Let's see what I'm up to in the next weeks.

### CODE REVIEW

**Comment by oegedijk** [comment]
@achimgaedke Awesome! Thank you so much! 

There were a ton of breaking changes to the new` bootstrap5`/`dash-bootstrap-components v1`, and it seems `explainerdashboard` used basically almost all of them :)

Will try to have a closer look the coming week. 

Would be nice if `dash-auth` also gets upgraded soon, so we can make the whole library with all dependencies `dash v2` compatible. 

Thanks again! That must have been quite an effort!

**Comment by achimgaedke** [comment]
just adding a conda environment file for easy testing.

```yaml
name: explainer
channels:
  - conda-forge
dependencies:
  - pip
  - wheel
  - numba
  # from explainerdashboard feedstock
  - click
  - dash>=2.3.1
  # installed below
  # - dash-auth
  - dash-bootstrap-components>=1
  - dash-core-components
  - dash-html-components
  - dash-table
  - dtreeviz
  - flask_simplelogin
  - joblib
  - jupyter-dash
  - numpy
  - orjson
  - oyaml
  - pandas
  - python
  - scikit-learn
  - shap
  - waitress
  # from dash-auth feedstock
  - chart-studio
  - dash
  - flask
  - flask-compress
  - flask-seasurf
  - itsdangerous
  - python
  - requests
  - retrying
  - ua-parser
  - pip:
    - git+https://github.com/jlondonob/dash-auth.git@dash-2
    - git+https://github.com/achimgaedke/explainerdashboard.git@bootstrap-5
```

**Comment by oegedijk** [comment]
tried to push some updates to this PR branch, but accidentally opened a new one: https://github.com/oegedijk/explainerdashboard/pull/214

**Comment by achimgaedke** [comment]
Might do something in the next days/week, just travelled to your time zone
:-)

**Comment by achimgaedke** [comment]
Ok, I've used git+https://github.com/oegedijk/explainerdashboard.git@bootstrap-5 and played a bit with it. Excellent!

Regarding `to_html`: Even the "Download" result for the static html export looks good.

Regarding `dash-auth`: For the use of conda/mamba, I could imagine it is better for now to use the main `dash-auth` version and add
```python
# the official dash_auth release uses deprecated imports
warnings.filterwarnings(
    "ignore",
    # NB the \n at the beginning of the message :-/
    r"\nThe dash_\w+_components package is deprecated",
    UserWarning,
    "dash_auth.plotly_auth",
)
```
before the import, so this project can use the package as it comes from pypi/conda feedstock for a while.

Ready to merge? What do you think?

**Comment by oegedijk** [comment]
closing this one as it has been handled by #214 instead...

thanks again!

**Pull request closed without merging**
