### PR TITLE
Add SimplifiedClassifierDashboard

### PR DESCRIPTION
**Pull request by mekomlusa**
Hey @oegedijk - thanks for this great tool! I found it quite useful, not only for better serving my clients, but also for myself analyzing "black box" model performance. 

I see that issue #19 is open and thought that I'd give it a try. I'm by no means good at the web front end, so didn't do much to make that one-page tab dazzling. But I did read your comments and tried to fulfill minimum requests as outlined in that issue. I've also attached a sample Jupyter notebook for demonstration - would love to hear your thoughts on this!

### CODE REVIEW

**Comment by oegedijk** [comment]
Cool! Thanks so much for contributing! I will have a closer look this weekend when I will have some more time!

**Comment by oegedijk** [comment]
Hej, had a chance to have a look. I like the structure, and always displaying confusion matrix plus a configurable other component.

A few suggestions: I think we can get rid of the global cutoff component: can simply connect the cutoff of the confusion matrix to the other one. Also think the alerts should not be needed? Some more elements can be hidden from the components to keep it even more simple I think. Let's also move it to the `dashboard_components/composites.py` module. Why did you pick PR AUC as the default? I think it's a bit less known than ROC AUC for example. Think we should also give the metrics table as an option. And then maybe add an option to  automatically load it from ExplainerDashboard like: `ExplainerDashboard(explainer, simple=True)`, which would also set `hide_header=True`.

What do you think?



So I would do something like this:

```
class SimplifiedClassifierDashboard(ExplainerComponent):
    def __init__(self, explainer, title="Simple Classifier Explainer", name=None,
                 classifier_custom_component='roc_auc', 
                 hide_confusionmatrix=False, hide_classifier_custom_component=False,
                 hide_shapsummary=False, hide_shapdependence=False,
                 hide_predindexselector=False, hide_predictionsummary=False,
                 hide_contributiongraph=False, **kwargs):
        """Composite of multiple classifier related components, on a single tab: 
            - confusion matrix
            - one other model quality indicator: choose from pr auc graph, precision graph, 
                    lift curve, classification graph, or roc auc graph
            - shap importance
            - shap dependence
            - index selector
            - index prediction summary
            - index shap contribution graph
        Args:
            explainer (Explainer): explainer object constructed with either
                        ClassifierExplainer() or RegressionExplainer()
            title (str, optional): Title of tab or page. Defaults to 
                        "Simple Classification Stats".
            name (str, optional): unique name to add to Component elements. 
                        If None then random uuid is generated to make sure 
                        it's unique. Defaults to None.
            simple_component (str, optional): custom classifier quality indicator 
                    supported by the ClassifierExplainer object. Valid values are: 
                    'roc_auc', 'metrics', pr_auc', 'precision_graph', 'lift_curve', 'classification'
            hide_confusionmatrix (bool, optional): hide ConfusionMatrixComponent
            hide_classifier_custom_component (bool, optional): hide the chosen classifier_custom_component
            hide_shapsummary (bool, optional): hide ShapSummaryComponent
            hide_shapdependence (bool, optional): hide ShapDependenceComponent
            hide_predindexselector (bool, optional): hide ClassifierRandomIndexComponent 
                or RegressionRandomIndexComponent
            hide_predictionsummary (bool, optional): hide ClassifierPredictionSummaryComponent
                or RegressionPredictionSummaryComponent
            hide_contributiongraph (bool, optional): hide ShapContributionsGraphComponent
        """
        super().__init__(explainer, title, name)
        
        self.confusionmatrix = ConfusionMatrixComponent(explainer, 
                                    **update_params(kwargs, hide_percentage=True, hide_selector=True))

        # select custom classifier report metric
        if classifier_custom_component == 'metrics':
            self.classifier_custom_component = ClassifierModelSummaryComponent(explainer, 
                                    **update_params(kwargs, hide_selector=True))
        elif classifier_custom_component == 'pr_auc':
            self.classifier_custom_component = PrAucComponent(explainer, 
                                    **update_params(kwargs, hide_selector=True))
        elif classifier_custom_component == 'precision_graph':
            self.classifier_custom_component = PrecisionComponent(explainer, 
                                    **update_params(kwargs, hide_selector=True))
        elif classifier_custom_component == 'lift_curve':
            self.classifier_custom_component = LiftCurveComponent(explainer, 
                                    **update_params(kwargs, hide_selector=True))
        elif classifier_custom_component == 'classifiction':
            self.classifier_custom_component = ClassificationComponent(explainer, 
                                    **update_params(kwargs, hide_selector=True))
        elif classifier_custom_component == 'roc_auc':
            self.classifier_custom_component = RocAucComponent(explainer, 
                                    **update_params(kwargs, hide_selector=True))
        else:
            raise ValueError(
                "ERROR: SimplifiedClassifierDashboard parameter classifier_custom_component "
                "should be in {'metrics', 'roc_auc', pr_auc', 'precision_graph', 'lift_curve', 'class_graph'} "
                f"but you passed {simple_custom_component}!")
            
        # SHAP summary & dependence
        self.shap_summary = ShapSummaryComponent(
            explainer, **update_params(kwargs, title="Shap Feature Importances", 
                                       hide_index=True, hide_selector=True, depth=None, hide_depth=True))
        self.shap_dependence = ShapDependenceComponent( 
            explainer, **update_params(kwargs, hide_selector=True, hide_index=True))

        # SHAP contribution, along with prediction summary
        self.index = ClassifierRandomIndexComponent(explainer, 
                                                    hide_selector=True, **kwargs)
        self.summary = ClassifierPredictionSummaryComponent(explainer, hide_index=True,
                                                            hide_selector=True, **kwargs)
        self.contributions = ShapContributionsGraphComponent(explainer, hide_index=True, hide_depth=True,
                                                             hide_selector=True, **kwargs)

        self.cutoffconnector = CutoffConnector(self.confusionmatrix, self.classifier_custom_component)
        self.connector = ShapSummaryDependenceConnector(self.shap_summary, self.shap_dependence)
        self.index_connector = IndexConnector(self.index, [self.summary, self.contributions])

    def layout(self):
        return html.Div([
            html.H1(self.title),
            html.H2("Model performance"),
            dbc.CardDeck([
                make_hideable(self.confusionmatrix.layout(),
                              hide=self.hide_confusionmatrix),
                make_hideable(self.classifier_custom_component.layout(),
                              hide=self.hide_classifier_custom_component),
            ], style=dict(marginTop=25, marginBottom=25)),
            html.H3("SHAP values"),
            dbc.CardDeck([
                make_hideable(self.shap_summary.layout(),
                              hide=self.hide_shapsummary),
                make_hideable(self.shap_dependence.layout(),
                              hide=self.hide_shapdependence),
            ], style=dict(marginTop=25, marginBottom=25)),
            html.H2("Individual predictions"),
            dbc.CardDeck([
                make_hideable(self.index.layout(),
                              hide=self.hide_predindexselector),
                make_hideable(self.summary.layout(),
                              hide=self.hide_predictionsummary),
            ], style=dict(marginBottom=25, marginTop=25)),
            dbc.CardDeck([
                make_hideable(self.contributions.layout(),
                              hide=self.hide_contributiongraph),
            ], style=dict(marginBottom=25, marginTop=25))
        ])
```

**Comment by mekomlusa** [comment]
Thanks for the feedback!

* For the global cutoff component - I didn't know that you could connect the confusion matrix with the customized one, so that would be perfect. Agree to remove.
* I put the alerts as notes so that users may understand how each part logically connects with the other (e.g. SHAP summary and dependence plots go together, but not necessarily the contribution graph). But if they seem redundant I'd agree with the removal.
* As for the PR-AUC plot, I found that my clients (i.e. business people) respond more positively to this one than the ROC curve.  For me, I look at ROC all the time. Okay with setting the default to be ROC.
* I like the metric table part! That would be a good alternative too - I was only thinking plots to gauge classifier performances, but that'd help too.
* I wasn't quite sure how to "automatically load it from ExplainerDashboard like: ExplainerDashboard(explainer, simple=True)", so would appreciate you pitching in this part.

Do I need to update my branch so that everything is in sync, as the code you demonstrated above? I've checked "allow edits by maintainers" so maybe it'd be easier if changes occur on your end?

**Comment by oegedijk** [comment]
Sorry for late reply, I have somehow screwed up my gcc installation on my mac, which meant I couldn't get shap to work anymore and couldn't actually test any changes. Regressing to shap==0.37 somehow did the trick. 

In any case:
- I moved the new dashboard to `composites.py` (and renamed it `SimplifiedClassifierComposite`)
- Added a `SimplifiedRegressionComposite` as well
- Added a flag `simple=True` to `ExplainerDashboard` which loads either `SimplifiedClassifierComposite` or `SimplifiedRegressionComposite`

Let me know if you have other ideas how to improve this! 

Otherwise will just have to write some tests and then we can merge it...

**Comment by mekomlusa** [comment]
Looks good to me. Thanks Oege! Looking forward to seeing the simplified versions up & running!

**Comment by oegedijk** [comment]
Okay, then I'll merge it, and add some tests later. Thanks again for your contribution!

**Comment by mekomlusa** [comment]
> Okay, then I'll merge it, and add some tests later. Thanks again for your contribution!

Cool! I could update the docs too so that people could start using it. Will wait for tests to pass first.

**Comment by oegedijk** [comment]
Let me know if you'd appreciate a Linkedin shoutout once I do the release! (just add me on Linkedin)

**Comment by oegedijk** [comment]
Released it here: https://github.com/oegedijk/explainerdashboard/releases/tag/v0.3.5

Thanks again for the contribution!

**Pull request merged**
