### PR TITLE
IndexSelector: use dynamic options

### PR DESCRIPTION
**Pull request by achimgaedke**
addresses loading timeouts for large datasets as described in #205

This is rough and ready, keen to get some feedback.

### CODE REVIEW

**Comment by oegedijk** [comment]
Cool, really nice approach! I actually noticed that dynamic dropdown thing in the documentation the other day as well. Very nifty!

Wonder if there are any performance tradeoffs though such that for small datasets (or rather maybe memory usage of `self.idxs`) we would use the old_fashioned dropdown and for larger ones the dynamic one.

But if it is perfomative enough than we can just default to the dynamic one...

**Comment by oegedijk** [comment]
This seems quite a bit slower, but has the benefit of being case sensitive:

image

**Comment by oegedijk** [comment]
Probably makes sense to wrap this into an `IndexDropdownComponent` so that is easy to replicate across components.

**Comment by oegedijk** [comment]
so this seems to work (check the feature input component index selector on the whatif tab)...

**Comment by oegedijk** [comment]
hmm, tests seem to fail on ubuntu. May check tomorrow...

**Comment by achimgaedke** [comment]
Btw, very pleased with the load time of the application utilising 1M data points.

**Comment by oegedijk** [comment]
Good question, and answer is that I forgot I had already written `IndexSelector`, but am apparently good at reinventing the wheel :)

**Comment by oegedijk** [comment]
Okay, I now extended the IndexSelector to all existing ExplainerComponents, and also added a functionality that that when the index is set directly the options simply get set to `[index]`. Before if the index was set from e.g. a random index selector and the chosen index was not already in the dropdown, it would not show. 

Since you have ready access to a million row index dataset, could you test performance of this `self.explainer.get_index_list().str.contains(search_value, case=False)][:self.max_idxs_in_dropdown].tolist()` vs the islice approach you had first?

I would like search to be case-insensitive, so if islice is much faster on big datasets, then we could add an `.index_list_lower()` and compare `search_value.lower()` to it...

**Comment by oegedijk** [comment]
bumped sklearn to 1.1 and python to 3.8 and voila tests are passing :)

**Comment by achimgaedke** [comment]
Thanks for keeping up the momentum on tbis and #217.

I'm keen on trying it out, but realistically i might have a chance to get
to it mid next week.

The next bottle necks for 100s of thousands of data points are the ROC and
PR AUC plots, esp the latter.

I haven't had a closer look for the reasons.

Not having the index repeatedly/at all in the JSON layout file is a great
step forward.

Cheers!

**Comment by achimgaedke** [comment]
I have reviewed the changes.

I propose some changes to the IndexSelector class from a software-engineering perspective, mainly from a consistency perspective and a bug in the conditions between the layout and the callback creation.

There's one difference in the use of `max_idxs_in_dropdown`: The original fix proposes to send dropdown options always as a callback result when requested. This version goes the middle way: allowing the dropdown values to be included in the app layout (multiple times).

Is a purely callback-based option too slow in some cases? If not, I'd suggest keeping only that one.

All in all, I'm worried about startup performance (and hitting a timeout with JSON becoming too slow to load) rather than runtime performance. Do we want two different thresholds?

I am not too concerned with the CPU performance difference of `iclice` vs `pandas.DataFrame.contains` for now. One would also need to consider memory consumption.

**Comment by oegedijk** [comment]
I think some subtle bug may have been introduced with the cleanup, but will have a closer look tomorrow..

thanks again for the work!

**Comment by oegedijk** [comment]
Alright, looks good to me, let's merge it!

Thanks again for this awesome initiave!

Will give you a shout out on linkedin once I'll release this version...

**Comment by oegedijk** [comment]
just released it as version 0.4.0

**Pull request merged**
