### PR TITLE
Dispatching the ExplainerHub app to /{self.base_route}/index

### PR DESCRIPTION
**Pull request by tunayokumus**
The current default base url path for Explainer path is hardcoded as "/index/". This PR changes this to /{self.base_route}/.
It also removes the routing of index to the "/" and changes that to {self.base_route}/index.

This is a rather quick implementation of the idea mentioned in  #130

### CODE REVIEW

**Comment by oegedijk** [comment]
Thanks for the PR!

I think the suggestion is fine, but let's try to implement it in a way that does not break any behaviour. People are probably running hubs which shouldn't suddenly break because they update the library. So this should be a new optional behaviour to load index on a different route...

**Comment by tunayokumus** [comment]
Indeed, that's only logical. I added a bool parameter to ExplainerHub. This way it shouldn't break any existing workflows.

**Comment by oegedijk** [comment]
Had a deeper look, and looks good! Nice minimally intrusive change! Thanks a lot!

I added `'index'` and `'hub'` to the list of `__reserved_names` and added an extra check when initializing, to make sure there are no name clashes with the new routes.

**Comment by oegedijk** [comment]
included in the latest release!

**Pull request merged**
